import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import browser, { __resetMockStore } from '../../src/__mocks__/webextension-polyfill';
const mocks = vi.hoisted(() => ({ executeUpload: vi.fn() }));
vi.mock('@src/application/sync-executor', () => ({ executeUpload: mocks.executeUpload }));
import { triggerDebouncedSync, handleDebounceAlarm, registerBookmarkListeners, resumePendingUpload } from '../../src/application/bookmark-monitor';
import { DEBOUNCE_ALARM } from '../../src/application/constants';
const alarm = { name: DEBOUNCE_ALARM, scheduledTime: 0 };

describe('durable bookmark changes', () => {
  beforeEach(async () => {
    vi.useFakeTimers(); __resetMockStore(); vi.clearAllMocks();
    await browser.storage.local.set({ webdav_url: 'https://dav.example.com', webdav_username: 'user', webdav_password: 'test', auto_sync_enabled: true });
    mocks.executeUpload.mockResolvedValue(true);
  });
  afterEach(() => { vi.clearAllTimers(); vi.useRealTimers(); });
  it('persists changes before scheduling the alarm', async () => {
    await triggerDebouncedSync();
    expect((await browser.storage.local.get('pending_bookmark_upload')).pending_bookmark_upload).toBeDefined();
    expect(browser.alarms.create).toHaveBeenCalledWith(DEBOUNCE_ALARM, expect.anything());
  });
  it('failed or suppressed uploads stay pending across worker restart', async () => {
    await triggerDebouncedSync(); mocks.executeUpload.mockResolvedValueOnce(false);
    await handleDebounceAlarm(alarm);
    const state = await browser.storage.local.get();
    expect(state.acknowledged_bookmark_upload).toBeUndefined();
    vi.mocked(browser.alarms.create).mockClear();
    await resumePendingUpload();
    expect(browser.alarms.create).toHaveBeenCalled();
  });
  it('an event during upload remains pending after the old operation finishes', async () => {
    await triggerDebouncedSync();
    const first = (await browser.storage.local.get('pending_bookmark_upload')).pending_bookmark_upload as { id: string };
    mocks.executeUpload.mockImplementationOnce(async () => { await triggerDebouncedSync(); return true; });
    await Promise.all([handleDebounceAlarm(alarm), handleDebounceAlarm(alarm)]);
    expect(mocks.executeUpload).toHaveBeenCalledTimes(1);
    const state = await browser.storage.local.get();
    expect(state.acknowledged_bookmark_upload).toBe(first.id);
    expect((state.pending_bookmark_upload as { id: string }).id).not.toBe(first.id);
    await handleDebounceAlarm(alarm);
    expect(mocks.executeUpload).toHaveBeenCalledTimes(2);
  });
  it('does not upload old pending work to a different target', async () => {
    await triggerDebouncedSync();
    await browser.storage.local.set({ webdav_url: 'https://other.example.com' });
    await handleDebounceAlarm(alarm);
    expect(mocks.executeUpload).not.toHaveBeenCalled();
  });
  it('ignores events generated by an unfinished restore', async () => {
    await browser.storage.local.set({ bookmark_recovery: { snapshotId: 1 } });
    await triggerDebouncedSync();
    expect(browser.alarms.create).not.toHaveBeenCalled();
  });
  it('registers all four bookmark event listeners', () => {
    registerBookmarkListeners();
    expect(browser.bookmarks.onCreated.addListener).toHaveBeenCalled();
    expect(browser.bookmarks.onRemoved.addListener).toHaveBeenCalled();
    expect(browser.bookmarks.onChanged.addListener).toHaveBeenCalled();
    expect(browser.bookmarks.onMoved.addListener).toHaveBeenCalled();
  });
});
